### ISSUE TITLE
HTTPS for AssetHost

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/AssetHost#12]
- [ ] Assethost can run on a dev machine
- [ ] There is clear documentation on how to run AssetHost on a dev machine 
- [x] asset URLs are HTTPS
- [x] we don't get any mixed content warnings in the major browsers because we're requesting assets using a different protocol (https <=> http)

**Comment by nakedsushi** [comment]
I pushed the https change to assethost Saturday night and seems to be 👌
