### ISSUE TITLE
Include a sample plugin

### ISSUE THREAD

**Issue by Ravenstine** [SCPR/AssetHost#21]
There should be example code for how to write a plugin to implement custom code for AssetHost.  It should demonstrate the basics of how to extend both Ruby & Backbone objects as well as CSS.  This work will then lead to packaging up the work for signifying which assets are OK for us to use at KPCC.

**Comment by Ravenstine** [comment]
Built out as:
https://github.com/SCPR/asset_host_kpcc

I decided to change this from being strictly a sample plugin to one for our own purposes(which right now contains the UI indicator for images that are good to use).  Someone who wants to write an AssetHost plugin could easily use it as a reference.

**Comment by Ravenstine** [comment]
Here's a screenshot:
![image](https://user-images.githubusercontent.com/5193330/27265788-5e50e1b0-544f-11e7-894d-f8c07b18edf5.png)

**Comment by nakedsushi** [comment]
In the README for that repo (which is what I'm assuming Public Media Kitchen will link to), can you specify what files one would need to change to adapt the plugin for their own uses? Or point out which files are specifically tailored for KPCC and what lines should be changed? I'm imaging someone coming to this with zero background about how we use Assethost.

**Comment by Ravenstine** [comment]
@nakedsushi If someone doesn't know enough about Ruby(or Rails for that matter) to understand what's going on in our plugin, it's not their business to be writing one in the first place.  I would rather provide a basic outline of instructions and a link to the [Rails guide on writing plugins](http://guides.rubyonrails.org/plugins.html) inside the SCPR/AssetHost repo.  Providing support for plugins is tentative anyway because it's entirely feasible to overhaul the AssetHost UI.

**Comment by nakedsushi** [comment]
@Ravenstine sounds reasonable. Let's link to those basic instructions if they're there in the asset_host_kpcc repo's readme so they're not confused about which repo is what.
