### ISSUE TITLE
Deploy Docker container in staging

### ISSUE THREAD

**Issue by Ravenstine** [SCPR/AssetHost#23]
We'll see what happens! :O  Estimating at a two as I have a feeling that it's not going to be as simple at first.  But maybe it will??

**Comment by nakedsushi** [comment]
Are you going to deploy it via Rancher?

________________________________

**Comment by Ravenstine** [comment]
Currently blocked until Rancher issues are resolved, as my IP cannot access the production database for testing on my end. :(

**Comment by Ravenstine** [comment]
A docker container has been successfully deployed to Rancher, but we still need to have our different services available through hostnames, especially since this is the only way we can connect to our Riak S3 cluster.  But the application itself is otherwise running properly on our existing production database.
